version: "3"
services:
  flutterapp:
    container_name: flutter_test_app_1
    network_mode: "host"
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./:/app
    stdin_open: true # docker run -i
    tty: true        # docker run -t